import type { Metadata } from "next";
import Link from "next/link";
import "../legal.css";

export const metadata: Metadata = {
  title: "terms of service — 2am",
  description:
    "the terms of service for 2am. myla is an ai companion, not a medical provider. always consult your healthcare provider for medical decisions.",
};

export default function TermsPage() {
  return (
    <main className="legal-page">
      <div className="legal-container">
        <Link href="/" className="legal-back">
          ← back to home
        </Link>
        <Link href="/" className="legal-logo">
          2am
        </Link>

        <h1 className="legal-title">terms of service</h1>
        <p className="legal-meta">last updated: april 2026</p>

        <section className="legal-section">
          <h2>what 2am is (and isn&apos;t)</h2>
          <p>
            2am is the judgment-free friend for your journey — whether
            you&apos;re trying, expecting, or navigating life as a new mom.
            powered by an ai companion named myla.
          </p>
          <p>
            2am is not a medical device, diagnostic tool, or substitute for
            professional medical care. myla is powered by artificial
            intelligence. she is not a doctor, nurse, midwife, therapist, or
            licensed healthcare provider.
          </p>
          <p>
            <strong>important:</strong> myla&apos;s responses are generated by
            ai and informed by medical literature, but they may contain
            errors. always consult your healthcare provider before making
            medical decisions. in an emergency, call 911 or go to your
            nearest emergency room.
          </p>
        </section>

        <section className="legal-section">
          <h2>using 2am</h2>
          <p>
            <strong>eligibility:</strong> you must be at least 18 years old to
            use 2am.
          </p>
          <p>
            <strong>your account:</strong> you&apos;re responsible for keeping
            your login credentials secure and for all activity on your
            account. one account per person. provide accurate information.
          </p>
          <p>
            <strong>acceptable use:</strong> you agree not to use 2am for any
            unlawful purpose, attempt to access other users&apos; accounts,
            reverse-engineer the app, use bots or scrapers, or attempt to
            bypass usage limits.
          </p>
        </section>

        <section className="legal-section">
          <h2>myla and ai</h2>
          <p>
            <strong>how myla works:</strong> when you send a message,
            it&apos;s sent to anthropic&apos;s api along with your
            conversation context. anthropic&apos;s ai generates a response
            based on myla&apos;s instructions, and the response is displayed
            in the app.
          </p>
          <p>
            <strong>ai limitations:</strong>
          </p>
          <ul>
            <li>
              myla can be wrong. ai can generate inaccurate, incomplete, or
              outdated information.
            </li>
            <li>
              myla doesn&apos;t have real-time information. she can&apos;t
              access the internet or your medical records.
            </li>
            <li>myla isn&apos;t a substitute for your healthcare provider.</li>
            <li>
              myla doesn&apos;t have personal experience. she&apos;s an ai,
              not a real person.
            </li>
          </ul>
          <p>
            <strong>your responsibility:</strong> you acknowledge that you
            will not make medical decisions based solely on myla&apos;s
            responses and will consult your healthcare provider for medical
            concerns.
          </p>
        </section>

        <section className="legal-section">
          <h2>content and data</h2>
          <p>
            you retain ownership of the messages you send to myla. by using
            the app, you grant us a limited license to process your messages
            for the purpose of generating responses.
          </p>
          <p>
            the app, its design, myla&apos;s character, and the &ldquo;can
            i&rdquo; database are owned by 2am (ac2 innovations llc).
          </p>
        </section>

        <section className="legal-section">
          <h2>subscription and payment</h2>
          <p>
            2am currently offers free access during our launch period. we
            plan to offer premium subscriptions in the future. safety-critical
            information will always remain free. no ads, ever.
          </p>
        </section>

        <section className="legal-section">
          <h2>disclaimers</h2>
          <p>
            <strong>medical disclaimer:</strong> 2am and myla do not provide
            medical advice, diagnosis, or treatment. the information provided
            is for general informational purposes only. always seek the
            advice of your physician or other qualified health provider.
          </p>
          <p>
            <strong>warranty disclaimer:</strong> 2am is provided &ldquo;as
            is&rdquo; and &ldquo;as available.&rdquo; we make no warranties
            regarding accuracy, reliability, or availability.
          </p>
          <p>
            <strong>limitation of liability:</strong> to the maximum extent
            permitted by law, 2am (ac2 innovations llc) shall not be liable
            for any indirect, incidental, special, or consequential damages
            arising from your use of the app. our total liability shall not
            exceed the amount you paid us in the 12 months preceding the
            claim, or $100, whichever is greater.
          </p>
        </section>

        <section className="legal-section">
          <h2>account termination</h2>
          <p>
            you can delete your account at any time. we reserve the right to
            suspend or terminate accounts that violate these terms.
          </p>
        </section>

        <section className="legal-section">
          <h2>changes</h2>
          <p>
            we may update these terms from time to time. if we make material
            changes, we&apos;ll notify you at least 30 days before they take
            effect.
          </p>
        </section>

        <section className="legal-section">
          <h2>governing law</h2>
          <p>
            these terms are governed by the laws of the state of florida. any
            disputes shall be resolved in the courts of lee county, florida.
          </p>
        </section>

        <section className="legal-section">
          <h2>contact us</h2>
          <p>
            email: <a href="mailto:support@hey2am.app">support@hey2am.app</a>
            <br />
            website: hey2am.app
          </p>
        </section>

        <footer className="legal-footer">
          © 2026 2am (ac2 innovations llc). built with care in florida.
          <div className="legal-footer-links">
            <Link href="/about">about</Link>
            <Link href="/blog">blog</Link>
            <Link href="/privacy">privacy</Link>
            <Link href="/terms">terms</Link>
          </div>
        </footer>
      </div>
    </main>
  );
}
